- name: Move kubeconfig to user home
  hosts: all
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
  tags:
    - move_kubeconfig_remote
  tasks:
    - name: Ensure .kube exists in ssh users' account
      ansible.builtin.file:
        path: "{{ cluster_config.ssh.ssh_home }}/.kube"
        state: directory
        mode: '0700'
        owner: "{{ cluster_config.ssh.ssh_user }}"
        group: "{{ cluster_config.ssh.ssh_user }}"
      become: false
      when: inventory_hostname not in groups['kube_etcd_servers']
    - name: Configure .kube/config files in user home
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ cluster_config.ssh.ssh_home }}/.kube/config"
        remote_src: yes
        owner: "{{ cluster_config.ssh.ssh_user }}"
        group: "{{ cluster_config.ssh.ssh_user }}"
        mode: '0700'
      become: true
      when: inventory_hostname in groups['kube_api_servers']
#    - name: restart kubelet for config changes
#      service:
#        name: kubelet
#        state: restarted
#      become: true
#      when: inventory_hostname not in groups['kube_etcd_servers']
