---
# Mirrors sections of apt-packages.sh that consume a version number
- name: Upgrade Kubernetes Cluster using Controlplane-0
  hosts: controlplane[0]
  gather_facts: true # Needs to know OS type
  become: true
  any_errors_fatal: true

  tasks:
    - name: Create directory for apt keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Remove old Kubernetes apt key and sources list
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        - /etc/apt/sources.list.d/kubernetes.list

    - name: Add Kubernetes apt repository key
      ansible.builtin.shell: |
        curl -fsSL "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_short_version }}/deb/Release.key" |
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_short_version }}/deb/ /"
        state: present
        filename: "kubernetes"

    - name: Install specific versions of kubelet, kubeadm, kubectl
      ansible.builtin.apt:
        name:
          - "kubelet={{ kubernetes_long_version }}"
          - "kubeadm={{ kubernetes_long_version }}"
          - "kubectl={{ kubernetes_long_version }}"
        state: present
        allow_change_held_packages: true
        allow_downgrade: true
        update_cache: true

    - name: Kubeadm Upgrade Plan
      ansible.builtin.shell:
        cmd: >
          kubeadm upgrade plan v{{ kubernetes_medium_version }}
      ignore_errors: true
      delegate_to: "{{ inventory_hostname }}"
      register: plan_output

    - name: Show plan output
      ansible.builtin.debug:
        msg: "{{ plan_output.stdout.splitlines() }}"

    - name: Confirm to continue
      ansible.builtin.pause:
        prompt: "Do you want to continue upgrading? (yes/no)"
      register: user_confirmation

    - name: Fail if user did not confirm
      ansible.builtin.fail:
        msg: "User chose not to continue."
      when: "user_confirmation.user_input | lower != 'yes'"

    - name: Kubeadm Upgrade Apply
      ansible.builtin.shell:
        cmd: >
          # K8s documentation recommends this step
          killall -s SIGTERM kube-apiserver # trigger a graceful kube-apiserver shutdown
          sleep 20 # wait a little bit to permit completing in-flight requests
          
          kubeadm upgrade apply v{{ kubernetes_medium_version }} -y
      ignore_errors: true
      delegate_to: "{{ inventory_hostname }}"
      register: upgrade_output

    - name: Show upgrade output
      ansible.builtin.debug:
        msg: "{{ upgrade_output.stdout.splitlines() }}"

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Restart kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
